spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/board
      driver-class-name: org.h2.Driver
      username: sa
      password: admin
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: create