spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:./data/board
      driver-class-name: org.h2.Driver
      username: sa
      password: admin